In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from sklearn import tree
from sklearn import preprocessing

In [2]:
train=pd.read_csv("D:\\LetsUpgrade\\Day 24\\train.csv")

In [3]:
pd.set_option("display.max_rows",100000)
pd.set_option("display.max_columns",100000)

In [4]:
train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
train.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,889.000000,889.000000,889.000000,889.000000,889.000000,889.000000,889.000000
mean,446.000000,0.382452,2.311586,32.699854,0.524184,0.382452,32.096681
std,256.998173,0.486260,0.834700,14.346821,1.103705,0.806761,49.697504
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,224.000000,0.000000,2.000000,22.000000,0.000000,0.000000,7.895800
50%,446.000000,0.000000,3.000000,32.000000,0.000000,0.000000,14.454200
75%,668.000000,1.000000,3.000000,45.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [6]:
train.shape

(889, 12)

In [7]:
train.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [8]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 889 entries, 0 to 888
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  889 non-null    int64
 1   Survived     889 non-null    int64
 2   Pclass       889 non-null    int64
 3   Name         889 non-null    object
 4   Sex          889 non-null    object
 5   Age          889 non-null    float64
 6   SibSp        889 non-null    int64
 7   Parch        889 non-null    int64
 8   Ticket       889 non-null    object
 9   Fare         889 non-null    float64
 10  Cabin        202 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.5+ KB

In [9]:
train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
dtype: int64

In [10]:
train.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [11]:
train.Age

0      22.00
1      38.00
2      26.00
3      35.00
4      35.00
5      45.00
6      54.00
7       2.00
8      27.00
9      14.00
10      4.00
11     58.00
12     20.00
13     39.00
14     14.00
15     55.00
16      2.00
17     45.00
18     31.00
19     45.00
20     35.00
21     34.00
22     15.00
23     28.00
24      8.00
25     38.00
26     45.00
27     19.00
28     45.00
29     45.00
30     40.00
31     45.00
32     45.00
33     66.00
34     28.00
35     42.00
36     45.00
37     21.00
38     18.00
39     14.00
40     40.00
41     27.00
42     45.00
43      3.00
44     19.00
45     45.00
46     45.00
47     45.00
48     45.00
49     18.00
50      7.00
51     21.00
52     49.00
53     29.00
54     65.00
55     45.00
56     21.00
57     28.50
58      5.00
59     11.00
60     22.00
61     45.00
62      4.00
63     45.00
64     45.00
65     29.00
66     19.00
67     17.00
68     26.00
69     32.00
70     16.00
71     21.00
72     26.00
73     32.00
74     25.00
75     45.00
76     45.00
77      0.83
78     30.00
79     22.00
80     29.00
81     45.00
82     28.00
83     17.00
84     33.00
85     16.00
86     45.00
87     23.00
88     24.00
89     29.00
90     20.00
91     46.00
92     26.00
93     59.00
94     45.00
95     71.00
96     23.00
97     34.00
98     34.00
99     28.00
100    45.00
101    21.00
102    33.00
103    37.00
104    28.00
105    21.00
106    45.00
107    38.00
108    45.00
109    47.00
110    14.50
111    22.00
112    20.00
113    17.00
114    21.00
115    70.50
116    29.00
117    24.00
118     2.00
119    21.00
120    45.00
121    32.50
122    32.50
123    54.00
124    12.00
125    45.00
126    24.00
127    45.00
128    45.00
129    33.00
130    20.00
131    47.00
132    29.00
133    25.00
134    23.00
135    19.00
136    37.00
137    16.00
138    24.00
139    45.00
140    22.00
141    24.00
142    19.00
143    18.00
144    19.00
145    27.00
146     9.00
147    36.50
148    42.00
149    51.00
150    22.00
151    55.50
152    40.50
153    45.00
154    51.00
155    16.00
156    30.00
157    45.00
158    45.00
159    44.00
160    40.00
161    26.00
162    17.00
163     1.00
164     9.00
165    45.00
166    45.00
167    45.00
168    28.00
169    61.00
170     4.00
171     1.00
172    21.00
173    56.00
174    18.00
175    45.00
176    50.00
177    30.00
178    36.00
179    45.00
180    45.00
181     9.00
182     1.00
183     4.00
184    45.00
185    45.00
186    45.00
187    40.00
188    36.00
189    32.00
190    19.00
191    19.00
192     3.00
193    44.00
194    58.00
195    45.00
196    42.00
197    45.00
198    24.00
199    28.00
200    45.00
201    34.00
202    45.50
203    18.00
204     2.00
205    32.00
206    26.00
207    16.00
208    40.00
209    24.00
210    35.00
211    22.00
212    30.00
213    45.00
214    31.00
215    27.00
216    42.00
217    32.00
218    30.00
219    16.00
220    27.00
221    51.00
222    45.00
223    38.00
224    22.00
225    19.00
226    20.50
227    18.00
228    45.00
229    35.00
230    29.00
231    59.00
232     5.00
233    24.00
234    45.00
235    44.00
236     8.00
237    19.00
238    33.00
239    45.00
240    45.00
241    29.00
242    22.00
243    30.00
244    44.00
245    25.00
246    24.00
247    37.00
248    54.00
249    45.00
250    29.00
251    62.00
252    30.00
253    41.00
254    29.00
255    45.00
256    30.00
257    35.00
258    50.00
259    45.00
260     3.00
261    52.00
262    40.00
263    45.00
264    36.00
265    16.00
266    25.00
267    58.00
268    35.00
269    45.00
270    25.00
271    41.00
272    37.00
273    45.00
274    63.00
275    45.00
276    45.00
277     7.00
278    35.00
279    65.00
280    28.00
281    16.00
282    19.00
283    45.00
284    33.00
285    30.00
286    22.00
287    42.00
288    22.00
289    26.00
290    19.00
291    36.00
292    24.00
293    24.00
294    45.00
295    23.50
296     2.00
297    45.00
298    50.00
299    45.00
300    45.00
301    19.00
302    45.00
303    45.00
304     0.92
305    45.00
306    17.00
307    30.00
308    30.00
309    24.00
310    18.00
311    26.00
312    28.00
313    43.00
314    26.00
315    24.00
316    54.00
317    31.00
318    40.00
319    22.00
320    27.00
321    30.00
322    22.00
323    45.00
324    36.00
325    61.00
326    36.00
327    31.00
328    16.00
329    45.00
330    45.50
331    38.00
332    16.00
333    45.00
334    45.00
335    29.00
336    41.00
337    45.00
338    45.00
339     2.00
340    24.00
341    28.00
342    25.00
343    36.00
344    24.00
345    40.00
346    45.00
347     3.00
348    42.00
349    23.00
350    45.00
351    15.00
352    25.00
353    45.00
354    28.00
355    22.00
356    38.00
357    45.00
358    45.00
359    40.00
360    29.00
361    45.00
362    35.00
363    45.00
364    30.00
365    60.00
366    45.00
367    45.00
368    24.00
369    25.00
370    18.00
371    19.00
372    22.00
373     3.00
374    45.00
375    22.00
376    27.00
377    20.00
378    19.00
379    42.00
380     1.00
381    32.00
382    35.00
383    45.00
384    18.00
385     1.00
386    36.00
387    45.00
388    17.00
389    36.00
390    21.00
391    28.00
392    23.00
393    24.00
394    22.00
395    31.00
396    46.00
397    23.00
398    28.00
399    39.00
400    26.00
401    21.00
402    28.00
403    20.00
404    34.00
405    51.00
406     3.00
407    21.00
408    45.00
409    45.00
410    45.00
411    33.00
412    45.00
413    44.00
414    45.00
415    34.00
416    18.00
417    30.00
418    10.00
419    45.00
420    21.00
421    29.00
422    28.00
423    18.00
424    45.00
425    28.00
426    19.00
427    45.00
428    32.00
429    28.00
430    45.00
431    42.00
432    17.00
433    50.00
434    14.00
435    21.00
436    24.00
437    64.00
438    31.00
439    45.00
440    20.00
441    25.00
442    28.00
443    45.00
444     4.00
445    13.00
446    34.00
447     5.00
448    52.00
449    36.00
450    45.00
451    30.00
452    49.00
453    45.00
454    29.00
455    65.00
456    45.00
457    50.00
458    45.00
459    48.00
460    34.00
461    47.00
462    48.00
463    45.00
464    38.00
465    45.00
466    56.00
467    45.00
468     0.75
469    45.00
470    38.00
471    33.00
472    23.00
473    22.00
474    45.00
475    34.00
476    29.00
477    22.00
478     2.00
479     9.00
480    45.00
481    50.00
482    63.00
483    25.00
484    45.00
485    35.00
486    58.00
487    30.00
488     9.00
489    45.00
490    21.00
491    55.00
492    71.00
493    21.00
494    45.00
495    54.00
496    45.00
497    25.00
498    24.00
499    17.00
500    21.00
501    45.00
502    37.00
503    16.00
504    18.00
505    33.00
506    45.00
507    28.00
508    26.00
509    29.00
510    45.00
511    36.00
512    54.00
513    24.00
514    47.00
515    34.00
516    45.00
517    36.00
518    32.00
519    30.00
520    22.00
521    45.00
522    44.00
523    45.00
524    40.50
525    50.00
526    45.00
527    39.00
528    23.00
529     2.00
530    45.00
531    17.00
532    45.00
533    30.00
534     7.00
535    45.00
536    30.00
537    45.00
538    22.00
539    36.00
540     9.00
541    11.00
542    32.00
543    50.00
544    64.00
545    19.00
546    45.00
547    33.00
548     8.00
549    17.00
550    27.00
551    45.00
552    22.00
553    22.00
554    62.00
555    48.00
556    45.00
557    39.00
558    36.00
559    45.00
560    40.00
561    28.00
562    45.00
563    45.00
564    24.00
565    19.00
566    29.00
567    45.00
568    32.00
569    62.00
570    53.00
571    36.00
572    45.00
573    16.00
574    19.00
575    34.00
576    39.00
577    45.00
578    32.00
579    25.00
580    39.00
581    54.00
582    36.00
583    45.00
584    18.00
585    47.00
586    60.00
587    22.00
588    45.00
589    35.00
590    52.00
591    47.00
592    45.00
593    37.00
594    36.00
595    45.00
596    49.00
597    45.00
598    49.00
599    24.00
600    45.00
601    45.00
602    44.00
603    35.00
604    36.00
605    30.00
606    27.00
607    22.00
608    40.00
609    39.00
610    45.00
611    45.00
612    45.00
613    35.00
614    24.00
615    34.00
616    26.00
617     4.00
618    26.00
619    27.00
620    42.00
621    20.00
622    21.00
623    21.00
624    61.00
625    57.00
626    21.00
627    26.00
628    45.00
629    80.00
630    51.00
631    32.00
632    45.00
633     9.00
634    28.00
635    32.00
636    31.00
637    41.00
638    45.00
639    20.00
640    24.00
641     2.00
642    45.00
643     0.75
644    48.00
645    19.00
646    56.00
647    45.00
648    23.00
649    45.00
650    18.00
651    21.00
652    45.00
653    18.00
654    24.00
655    45.00
656    32.00
657    23.00
658    58.00
659    50.00
660    40.00
661    47.00
662    36.00
663    20.00
664    32.00
665    25.00
666    45.00
667    43.00
668    45.00
669    40.00
670    31.00
671    70.00
672    31.00
673    45.00
674    18.00
675    24.50
676    18.00
677    43.00
678    36.00
679    45.00
680    27.00
681    20.00
682    14.00
683    60.00
684    25.00
685    14.00
686    19.00
687    18.00
688    15.00
689    31.00
690     4.00
691    45.00
692    25.00
693    60.00
694    52.00
695    44.00
696    45.00
697    49.00
698    42.00
699    18.00
700    35.00
701    18.00
702    25.00
703    26.00
704    39.00
705    45.00
706    42.00
707    22.00
708    45.00
709    24.00
710    45.00
711    48.00
712    29.00
713    52.00
714    19.00
715    38.00
716    27.00
717    45.00
718    33.00
719     6.00
720    17.00
721    34.00
722    50.00
723    27.00
724    20.00
725    30.00
726    45.00
727    25.00
728    25.00
729    29.00
730    11.00
731    45.00
732    23.00
733    23.00
734    28.50
735    48.00
736    35.00
737    45.00
738    45.00
739    45.00
740    36.00
741    21.00
742    24.00
743    31.00
744    70.00
745    16.00
746    30.00
747    19.00
748    31.00
749     4.00
750     6.00
751    33.00
752    23.00
753    48.00
754     0.67
755    28.00
756    18.00
757    34.00
758    33.00
759    45.00
760    41.00
761    20.00
762    36.00
763    16.00
764    51.00
765    45.00
766    30.50
767    45.00
768    32.00
769    24.00
770    48.00
771    57.00
772    45.00
773    54.00
774    18.00
775    45.00
776     5.00
777    45.00
778    43.00
779    13.00
780    17.00
781    29.00
782    45.00
783    25.00
784    25.00
785    18.00
786     8.00
787     1.00
788    46.00
789    45.00
790    16.00
791    45.00
792    45.00
793    25.00
794    39.00
795    49.00
796    31.00
797    30.00
798    30.00
799    34.00
800    31.00
801    11.00
802     0.42
803    27.00
804    31.00
805    39.00
806    18.00
807    39.00
808    33.00
809    26.00
810    39.00
811    35.00
812     6.00
813    30.50
814    45.00
815    23.00
816    31.00
817    43.00
818    10.00
819    52.00
820    27.00
821    38.00
822    27.00
823     2.00
824    45.00
825    45.00
826     1.00
827    45.00
828    15.00
829     0.83
830    45.00
831    23.00
832    18.00
833    39.00
834    21.00
835    45.00
836    32.00
837    45.00
838    20.00
839    16.00
840    30.00
841    34.50
842    17.00
843    42.00
844    45.00
845    35.00
846    28.00
847    45.00
848     4.00
849    74.00
850     9.00
851    16.00
852    44.00
853    18.00
854    45.00
855    51.00
856    24.00
857    45.00
858    41.00
859    21.00
860    48.00
861    45.00
862    24.00
863    42.00
864    27.00
865    31.00
866    45.00
867     4.00
868    26.00
869    47.00
870    33.00
871    47.00
872    28.00
873    15.00
874    20.00
875    19.00
876    45.00
877    56.00
878    25.00
879    33.00
880    22.00
881    28.00
882    25.00
883    39.00
884    27.00
885    19.00
886    45.00
887    26.00
888    32.00
Name: Age, dtype: float64

In [12]:
train['Age'].mean()

32.69985376827896

In [13]:
new_age=np.where(train['Age'].isnull(),32,train['Age'])

In [14]:
train['Age']=new_age

In [15]:
train.Age

0      22.00
1      38.00
2      26.00
3      35.00
4      35.00
5      45.00
6      54.00
7       2.00
8      27.00
9      14.00
10      4.00
11     58.00
12     20.00
13     39.00
14     14.00
15     55.00
16      2.00
17     45.00
18     31.00
19     45.00
20     35.00
21     34.00
22     15.00
23     28.00
24      8.00
25     38.00
26     45.00
27     19.00
28     45.00
29     45.00
30     40.00
31     45.00
32     45.00
33     66.00
34     28.00
35     42.00
36     45.00
37     21.00
38     18.00
39     14.00
40     40.00
41     27.00
42     45.00
43      3.00
44     19.00
45     45.00
46     45.00
47     45.00
48     45.00
49     18.00
50      7.00
51     21.00
52     49.00
53     29.00
54     65.00
55     45.00
56     21.00
57     28.50
58      5.00
59     11.00
60     22.00
61     45.00
62      4.00
63     45.00
64     45.00
65     29.00
66     19.00
67     17.00
68     26.00
69     32.00
70     16.00
71     21.00
72     26.00
73     32.00
74     25.00
75     45.00
76     45.00
77      0.83
78     30.00
79     22.00
80     29.00
81     45.00
82     28.00
83     17.00
84     33.00
85     16.00
86     45.00
87     23.00
88     24.00
89     29.00
90     20.00
91     46.00
92     26.00
93     59.00
94     45.00
95     71.00
96     23.00
97     34.00
98     34.00
99     28.00
100    45.00
101    21.00
102    33.00
103    37.00
104    28.00
105    21.00
106    45.00
107    38.00
108    45.00
109    47.00
110    14.50
111    22.00
112    20.00
113    17.00
114    21.00
115    70.50
116    29.00
117    24.00
118     2.00
119    21.00
120    45.00
121    32.50
122    32.50
123    54.00
124    12.00
125    45.00
126    24.00
127    45.00
128    45.00
129    33.00
130    20.00
131    47.00
132    29.00
133    25.00
134    23.00
135    19.00
136    37.00
137    16.00
138    24.00
139    45.00
140    22.00
141    24.00
142    19.00
143    18.00
144    19.00
145    27.00
146     9.00
147    36.50
148    42.00
149    51.00
150    22.00
151    55.50
152    40.50
153    45.00
154    51.00
155    16.00
156    30.00
157    45.00
158    45.00
159    44.00
160    40.00
161    26.00
162    17.00
163     1.00
164     9.00
165    45.00
166    45.00
167    45.00
168    28.00
169    61.00
170     4.00
171     1.00
172    21.00
173    56.00
174    18.00
175    45.00
176    50.00
177    30.00
178    36.00
179    45.00
180    45.00
181     9.00
182     1.00
183     4.00
184    45.00
185    45.00
186    45.00
187    40.00
188    36.00
189    32.00
190    19.00
191    19.00
192     3.00
193    44.00
194    58.00
195    45.00
196    42.00
197    45.00
198    24.00
199    28.00
200    45.00
201    34.00
202    45.50
203    18.00
204     2.00
205    32.00
206    26.00
207    16.00
208    40.00
209    24.00
210    35.00
211    22.00
212    30.00
213    45.00
214    31.00
215    27.00
216    42.00
217    32.00
218    30.00
219    16.00
220    27.00
221    51.00
222    45.00
223    38.00
224    22.00
225    19.00
226    20.50
227    18.00
228    45.00
229    35.00
230    29.00
231    59.00
232     5.00
233    24.00
234    45.00
235    44.00
236     8.00
237    19.00
238    33.00
239    45.00
240    45.00
241    29.00
242    22.00
243    30.00
244    44.00
245    25.00
246    24.00
247    37.00
248    54.00
249    45.00
250    29.00
251    62.00
252    30.00
253    41.00
254    29.00
255    45.00
256    30.00
257    35.00
258    50.00
259    45.00
260     3.00
261    52.00
262    40.00
263    45.00
264    36.00
265    16.00
266    25.00
267    58.00
268    35.00
269    45.00
270    25.00
271    41.00
272    37.00
273    45.00
274    63.00
275    45.00
276    45.00
277     7.00
278    35.00
279    65.00
280    28.00
281    16.00
282    19.00
283    45.00
284    33.00
285    30.00
286    22.00
287    42.00
288    22.00
289    26.00
290    19.00
291    36.00
292    24.00
293    24.00
294    45.00
295    23.50
296     2.00
297    45.00
298    50.00
299    45.00
300    45.00
301    19.00
302    45.00
303    45.00
304     0.92
305    45.00
306    17.00
307    30.00
308    30.00
309    24.00
310    18.00
311    26.00
312    28.00
313    43.00
314    26.00
315    24.00
316    54.00
317    31.00
318    40.00
319    22.00
320    27.00
321    30.00
322    22.00
323    45.00
324    36.00
325    61.00
326    36.00
327    31.00
328    16.00
329    45.00
330    45.50
331    38.00
332    16.00
333    45.00
334    45.00
335    29.00
336    41.00
337    45.00
338    45.00
339     2.00
340    24.00
341    28.00
342    25.00
343    36.00
344    24.00
345    40.00
346    45.00
347     3.00
348    42.00
349    23.00
350    45.00
351    15.00
352    25.00
353    45.00
354    28.00
355    22.00
356    38.00
357    45.00
358    45.00
359    40.00
360    29.00
361    45.00
362    35.00
363    45.00
364    30.00
365    60.00
366    45.00
367    45.00
368    24.00
369    25.00
370    18.00
371    19.00
372    22.00
373     3.00
374    45.00
375    22.00
376    27.00
377    20.00
378    19.00
379    42.00
380     1.00
381    32.00
382    35.00
383    45.00
384    18.00
385     1.00
386    36.00
387    45.00
388    17.00
389    36.00
390    21.00
391    28.00
392    23.00
393    24.00
394    22.00
395    31.00
396    46.00
397    23.00
398    28.00
399    39.00
400    26.00
401    21.00
402    28.00
403    20.00
404    34.00
405    51.00
406     3.00
407    21.00
408    45.00
409    45.00
410    45.00
411    33.00
412    45.00
413    44.00
414    45.00
415    34.00
416    18.00
417    30.00
418    10.00
419    45.00
420    21.00
421    29.00
422    28.00
423    18.00
424    45.00
425    28.00
426    19.00
427    45.00
428    32.00
429    28.00
430    45.00
431    42.00
432    17.00
433    50.00
434    14.00
435    21.00
436    24.00
437    64.00
438    31.00
439    45.00
440    20.00
441    25.00
442    28.00
443    45.00
444     4.00
445    13.00
446    34.00
447     5.00
448    52.00
449    36.00
450    45.00
451    30.00
452    49.00
453    45.00
454    29.00
455    65.00
456    45.00
457    50.00
458    45.00
459    48.00
460    34.00
461    47.00
462    48.00
463    45.00
464    38.00
465    45.00
466    56.00
467    45.00
468     0.75
469    45.00
470    38.00
471    33.00
472    23.00
473    22.00
474    45.00
475    34.00
476    29.00
477    22.00
478     2.00
479     9.00
480    45.00
481    50.00
482    63.00
483    25.00
484    45.00
485    35.00
486    58.00
487    30.00
488     9.00
489    45.00
490    21.00
491    55.00
492    71.00
493    21.00
494    45.00
495    54.00
496    45.00
497    25.00
498    24.00
499    17.00
500    21.00
501    45.00
502    37.00
503    16.00
504    18.00
505    33.00
506    45.00
507    28.00
508    26.00
509    29.00
510    45.00
511    36.00
512    54.00
513    24.00
514    47.00
515    34.00
516    45.00
517    36.00
518    32.00
519    30.00
520    22.00
521    45.00
522    44.00
523    45.00
524    40.50
525    50.00
526    45.00
527    39.00
528    23.00
529     2.00
530    45.00
531    17.00
532    45.00
533    30.00
534     7.00
535    45.00
536    30.00
537    45.00
538    22.00
539    36.00
540     9.00
541    11.00
542    32.00
543    50.00
544    64.00
545    19.00
546    45.00
547    33.00
548     8.00
549    17.00
550    27.00
551    45.00
552    22.00
553    22.00
554    62.00
555    48.00
556    45.00
557    39.00
558    36.00
559    45.00
560    40.00
561    28.00
562    45.00
563    45.00
564    24.00
565    19.00
566    29.00
567    45.00
568    32.00
569    62.00
570    53.00
571    36.00
572    45.00
573    16.00
574    19.00
575    34.00
576    39.00
577    45.00
578    32.00
579    25.00
580    39.00
581    54.00
582    36.00
583    45.00
584    18.00
585    47.00
586    60.00
587    22.00
588    45.00
589    35.00
590    52.00
591    47.00
592    45.00
593    37.00
594    36.00
595    45.00
596    49.00
597    45.00
598    49.00
599    24.00
600    45.00
601    45.00
602    44.00
603    35.00
604    36.00
605    30.00
606    27.00
607    22.00
608    40.00
609    39.00
610    45.00
611    45.00
612    45.00
613    35.00
614    24.00
615    34.00
616    26.00
617     4.00
618    26.00
619    27.00
620    42.00
621    20.00
622    21.00
623    21.00
624    61.00
625    57.00
626    21.00
627    26.00
628    45.00
629    80.00
630    51.00
631    32.00
632    45.00
633     9.00
634    28.00
635    32.00
636    31.00
637    41.00
638    45.00
639    20.00
640    24.00
641     2.00
642    45.00
643     0.75
644    48.00
645    19.00
646    56.00
647    45.00
648    23.00
649    45.00
650    18.00
651    21.00
652    45.00
653    18.00
654    24.00
655    45.00
656    32.00
657    23.00
658    58.00
659    50.00
660    40.00
661    47.00
662    36.00
663    20.00
664    32.00
665    25.00
666    45.00
667    43.00
668    45.00
669    40.00
670    31.00
671    70.00
672    31.00
673    45.00
674    18.00
675    24.50
676    18.00
677    43.00
678    36.00
679    45.00
680    27.00
681    20.00
682    14.00
683    60.00
684    25.00
685    14.00
686    19.00
687    18.00
688    15.00
689    31.00
690     4.00
691    45.00
692    25.00
693    60.00
694    52.00
695    44.00
696    45.00
697    49.00
698    42.00
699    18.00
700    35.00
701    18.00
702    25.00
703    26.00
704    39.00
705    45.00
706    42.00
707    22.00
708    45.00
709    24.00
710    45.00
711    48.00
712    29.00
713    52.00
714    19.00
715    38.00
716    27.00
717    45.00
718    33.00
719     6.00
720    17.00
721    34.00
722    50.00
723    27.00
724    20.00
725    30.00
726    45.00
727    25.00
728    25.00
729    29.00
730    11.00
731    45.00
732    23.00
733    23.00
734    28.50
735    48.00
736    35.00
737    45.00
738    45.00
739    45.00
740    36.00
741    21.00
742    24.00
743    31.00
744    70.00
745    16.00
746    30.00
747    19.00
748    31.00
749     4.00
750     6.00
751    33.00
752    23.00
753    48.00
754     0.67
755    28.00
756    18.00
757    34.00
758    33.00
759    45.00
760    41.00
761    20.00
762    36.00
763    16.00
764    51.00
765    45.00
766    30.50
767    45.00
768    32.00
769    24.00
770    48.00
771    57.00
772    45.00
773    54.00
774    18.00
775    45.00
776     5.00
777    45.00
778    43.00
779    13.00
780    17.00
781    29.00
782    45.00
783    25.00
784    25.00
785    18.00
786     8.00
787     1.00
788    46.00
789    45.00
790    16.00
791    45.00
792    45.00
793    25.00
794    39.00
795    49.00
796    31.00
797    30.00
798    30.00
799    34.00
800    31.00
801    11.00
802     0.42
803    27.00
804    31.00
805    39.00
806    18.00
807    39.00
808    33.00
809    26.00
810    39.00
811    35.00
812     6.00
813    30.50
814    45.00
815    23.00
816    31.00
817    43.00
818    10.00
819    52.00
820    27.00
821    38.00
822    27.00
823     2.00
824    45.00
825    45.00
826     1.00
827    45.00
828    15.00
829     0.83
830    45.00
831    23.00
832    18.00
833    39.00
834    21.00
835    45.00
836    32.00
837    45.00
838    20.00
839    16.00
840    30.00
841    34.50
842    17.00
843    42.00
844    45.00
845    35.00
846    28.00
847    45.00
848     4.00
849    74.00
850     9.00
851    16.00
852    44.00
853    18.00
854    45.00
855    51.00
856    24.00
857    45.00
858    41.00
859    21.00
860    48.00
861    45.00
862    24.00
863    42.00
864    27.00
865    31.00
866    45.00
867     4.00
868    26.00
869    47.00
870    33.00
871    47.00
872    28.00
873    15.00
874    20.00
875    19.00
876    45.00
877    56.00
878    25.00
879    33.00
880    22.00
881    28.00
882    25.00
883    39.00
884    27.00
885    19.00
886    45.00
887    26.00
888    32.00
Name: Age, dtype: float64

In [16]:
label_encoder=preprocessing.LabelEncoder()

In [17]:
encoded_sex=label_encoder.fit_transform(train['Sex'])

In [18]:
encoded_sex

array([1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 1, 1])

# Model_1

In [19]:
tree_model=tree.DecisionTreeClassifier()

In [20]:
tree_model.fit(X=pd.DataFrame(encoded_sex),y=train['Survived'])

DecisionTreeClassifier()

In [21]:
with open("DecisionTree.dot","w")as f:
    f=tree.export_graphviz(tree_model,feature_names=['Sex'],out_file=f);

# Model_2

In [22]:
tree_model.fit(pd.DataFrame([encoded_sex,train['Pclass']]).T,y=train['Survived'])

DecisionTreeClassifier()

In [23]:
with open("DecisionTree1.dot","w") as f:
    f=tree.export_graphviz(tree_model,feature_names=["Sex","Pclass"],out_file=f);

# Model_3

In [24]:
predictors=pd.DataFrame([encoded_sex, train["Pclass"], train["Age"],train["Fare"]]).T

In [25]:
# 8 depth has given here as we have 4 independent variable and 2 catergories of depenedent varibale 
#i.e syrvived or not thats why 4*2=8 has given
tree_model=tree.DecisionTreeClassifier(max_depth=8)

In [26]:
tree_model.fit(X=predictors,y=train['Survived'])

DecisionTreeClassifier(max_depth=8)

In [27]:
with open("DecisionTree3.dot","w") as f:
    f=tree.export_graphviz(tree_model,feature_names=["Sex","Pclass","Age","Fare"],out_file=f);

# How to check the model accuracy

In [28]:
tree_model.score(X=predictors,y=train['Survived'])

0.8965129358830146

# How to predict the using Test Data

In [29]:
test=pd.read_csv("D:\\LetsUpgrade\\Day 24\\test.csv")

In [30]:
test.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,S

In [32]:
new_age=np.where(test["Age"].isnull,28,test['Age'])

In [33]:
test['Age']=new_age

In [34]:
encoded_sex_test=label_encoder.fit_transform(test['Sex'])

In [35]:
encoded_sex_test

array([1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1])

In [36]:
test_features=pd.DataFrame([encoded_sex_test,test['Pclass'],test['Age'],test['Fare']]).T

In [37]:
test_preds=tree_model.predict(X=test_features)

In [38]:
test_preds

array([0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0],
      dtype=int64)

In [39]:
Predicted_output=pd.DataFrame({"PassengerId":test['PassengerId'],"Survived":test_preds})

In [40]:
Predicted_output

     PassengerId  Survived
0            892         0
1            893         1
2            894         0
3            895         0
4            896         0
5            897         0
6            898         0
7            899         0
8            900         1
9            901         0
10           902         0
11           903         1
12           904         1
13           905         0
14           906         1
15           907         1
16           908         0
17           909         0
18           910         0
19           911         1
20           912         1
21           913         0
22           914         1
23           915         1
24           916         1
25           917         0
26           918         1
27           919         0
28           920         1
29           921         0
30           922         0
31           923         0
32           924         1
33           925         0
34           926         1
35           927         0
36           928         0
37           929         0
38           930         0
39           931         0
40           932         0
41           933         1
42           934         0
43           935         1
44           936         1
45           937         0
46           938         1
47           939         0
48           940         1
49           941         1
50           942         1
51           943         0
52           944         1
53           945         1
54           946         0
55           947         0
56           948         0
57           949         0
58           950         0
59           951         1
60           952         0
61           953         0
62           954         0
63           955         1
64           956         1
65           957         1
66           958         1
67           959         0
68           960         1
69           961         1
70           962         1
71           963         0
72           964         0
73           965         1
74           966         1
75           967         1
76           968         0
77           969         1
78           970         0
79           971         1
80           972         0
81           973         1
82           974         1
83           975         0
84           976         0
85           977         0
86           978         1
87           979         0
88           980         1
89           981         0
90           982         0
91           983         0
92           984         1
93           985         0
94           986         1
95           987         0
96           988         1
97           989         0
98           990         1
99           991         0
100          992         1
101          993         0
102          994         0
103          995         0
104          996         0
105          997         0
106          998         0
107          999         0
108         1000         0
109         1001         0
110         1002         0
111         1003         1
112         1004         1
113         1005         1
114         1006         1
115         1007         0
116         1008         0
117         1009         1
118         1010         1
119         1011         1
120         1012         1
121         1013         0
122         1014         1
123         1015         0
124         1016         0
125         1017         1
126         1018         0
127         1019         1
128         1020         0
129         1021         0
130         1022         0
131         1023         1
132         1024         0
133         1025         0
134         1026         0
135         1027         0
136         1028         0
137         1029         0
138         1030         0
139         1031         0
140         1032         0
141         1033         0
142         1034         1
143         1035         0
144         1036         1
145         1037         0
146         1038         0
147         1039         0
148         1040         1
149         1041         0
150         1042         1
151         1043         0
152         1045         0
153         1046         0
154         1047         0
155         1048         1
156         1049         1
157         1050         1
158         1051         0
159         1052         1
160         1053         0
161         1054         1
162         1055         0
163         1056         0
164         1057         1
165         1058         0
166         1059         0
167         1060         1
168         1061         0
169         1062         0
170         1063         0
171         1064         0
172         1065         0
173         1066         0
174         1067         1
175         1068         1
176         1069         1
177         1070         1
178         1071         1
179         1072         0
180         1073         1
181         1074         1
182         1075         0
183         1076         1
184         1077         0
185         1078         1
186         1079         0
187         1080         0
188         1081         0
189         1082         0
190         1083         1
191         1084         0
192         1085         0
193         1086         0
194         1087         0
195         1088         1
196         1089         1
197         1090         0
198         1091         0
199         1092         1
200         1093         0
201         1094         1
202         1095         1
203         1096         0
204         1097         1
205         1098         1
206         1099         0
207         1100         1
208         1101         0
209         1102         0
210         1103         0
211         1104         0
212         1105         1
213         1106         1
214         1107         0
215         1108         1
216         1109         1
217         1110         1
218         1111         0
219         1112         1
220         1113         0
221         1114         1
222         1115         0
223         1116         1
224         1117         0
225         1118         0
226         1119         1
227         1120         0
228         1121         0
229         1122         0
230         1123         1
231         1124         0
232         1125         0
233         1126         1
234         1127         0
235         1128         1
236         1129         0
237         1130         1
238         1131         1
239         1132         1
240         1133         1
241         1134         1
242         1135         0
243         1136         0
244         1137         0
245         1138         1
246         1139         0
247         1140         1
248         1141         0
249         1142         1
250         1143         0
251         1144         1
252         1145         0
253         1146         0
254         1147         0
255         1148         0
256         1149         0
257         1150         1
258         1151         0
259         1152         0
260         1153         0
261         1154         1
262         1155         0
263         1156         0
264         1157         0
265         1158         0
266         1159         0
267         1160         0
268         1161         0
269         1162         1
270         1163         0
271         1164         1
272         1165         1
273         1166         0
274         1167         1
275         1168         0
276         1169         0
277         1170         0
278         1171         0
279         1172         0
280         1173         0
281         1174         1
282         1175         0
283         1176         1
284         1177         0
285         1178         0
286         1179         1
287         1180         0
288         1181         0
289         1182         0
290         1183         0
291         1184         0
292         1185         1
293         1186         0
294         1187         0
295         1188         1
296         1189         0
297         1190         0
298         1191         0
299         1192         0
300         1193         0
301         1194         0
302         1195         0
303         1196         1
304         1197         1
305         1198         1
306         1199         0
307         1200         1
308         1201         0
309         1202         0
310         1203         0
311         1204         0
312         1205         1
313         1206         1
314         1207         1
315         1208         1
316         1209         0
317         1210         0
318         1211         0
319         1212         0
320         1213         0
321         1214         0
322         1215         1
323         1216         1
324         1217         0
325         1218         1
326         1219         1
327         1220         0
328         1221         0
329         1222         1
330         1223         1
331         1224         0
332         1225         1
333         1226         0
334         1227         1
335         1228         0
336         1229         0
337         1230         0
338         1231         0
339         1232         0
340         1233         0
341         1234         0
342         1235         1
343         1236         0
344         1237         1
345         1238         0
346         1239         1
347         1240         0
348         1241         1
349         1242         1
350         1243         0
351         1244         0
352         1245         0
353         1246         1
354         1247         1
355         1248         1
356         1249         0
357         1250         0
358         1251         1
359         1252         0
360         1253         1
361         1254         1
362         1255         0
363         1256         1
364         1257         0
365         1258         0
366         1259         0
367         1260         1
368         1261         0
369         1262         0
370         1263         1
371         1264         0
372         1265         0
373         1266         1
374         1267         1
375         1268         0
376         1269         0
377         1270         0
378         1271         0
379         1272         0
380         1273         0
381         1274         0
382         1275         1
383         1276         0
384         1277         1
385         1278         0
386         1279         0
387         1280         0
388         1281         0
389         1282         1
390         1283         1
391         1284         0
392         1285         0
393         1286         0
394         1287         1
395         1288         0
396         1289         1
397         1290         0
398         1291         0
399         1292         1
400         1293         0
401         1294         1
402         1295         0
403         1296         1
404         1297         0
405         1298         0
406         1299         1
407         1300         1
408         1301         0
409         1302         1
410         1303         1
411         1304         1
412         1305         0
413         1306         1
414         1307         0
415         1308         0
416         1309         0

# To convert into a Csv file

In [41]:
Predicted_output.to_csv("Output.csv",index=False);

# Random Forest
___ It is the ensemble of decision tree which is used to find the important variable for DT___

In [42]:
train.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [43]:
label_encoder=preprocessing.LabelEncoder()

In [46]:
train['Sex']=label_encoder.fit_transform(train["Sex"])

In [44]:
train['Embarked']=label_encoder.fit_transform(train["Embarked"])

In [47]:
train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",1,22.0,1,0,A/5 21171,7.2500,NaN,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,38.0,1,0,PC 17599,71.2833,C85,0
2,3,1,3,"Heikkinen, Miss. Laina",0,26.0,0,0,STON/O2. 3101282,7.9250,NaN,2
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,35.0,1,0,113803,53.1000,C123,2
4,5,0,3,"Allen, Mr. William Henry",1,35.0,0,0,373450,8.0500,NaN,2

In [48]:
train.Embarked

0      2
1      0
2      2
3      2
4      2
5      1
6      2
7      2
8      2
9      0
10     2
11     2
12     2
13     2
14     2
15     2
16     1
17     2
18     2
19     0
20     2
21     2
22     1
23     2
24     2
25     2
26     0
27     2
28     1
29     2
30     0
31     0
32     1
33     2
34     0
35     2
36     0
37     2
38     2
39     0
40     2
41     2
42     0
43     0
44     1
45     2
46     1
47     1
48     0
49     2
50     2
51     2
52     0
53     2
54     0
55     2
56     2
57     0
58     2
59     2
60     0
61     2
62     2
63     0
64     0
65     2
66     2
67     2
68     2
69     2
70     2
71     2
72     0
73     2
74     2
75     2
76     2
77     2
78     2
79     2
80     2
81     1
82     2
83     2
84     2
85     2
86     2
87     2
88     2
89     2
90     2
91     2
92     2
93     2
94     2
95     0
96     0
97     2
98     2
99     2
100    2
101    2
102    2
103    2
104    2
105    2
106    2
107    2
108    1
109    2
110    0
111    2
112    2
113    0
114    2
115    1
116    2
117    0
118    2
119    2
120    2
121    0
122    2
123    2
124    0
125    1
126    2
127    0
128    2
129    0
130    2
131    2
132    2
133    2
134    0
135    2
136    2
137    2
138    0
139    0
140    2
141    2
142    1
143    2
144    2
145    2
146    2
147    2
148    2
149    2
150    2
151    2
152    2
153    2
154    0
155    1
156    2
157    2
158    2
159    2
160    2
161    2
162    2
163    2
164    2
165    2
166    2
167    2
168    2
169    2
170    1
171    2
172    2
173    0
174    2
175    2
176    0
177    2
178    2
179    2
180    0
181    2
182    2
183    2
184    2
185    1
186    2
187    1
188    2
189    2
190    2
191    2
192    2
193    0
194    0
195    1
196    2
197    1
198    2
199    2
200    2
201    2
202    0
203    2
204    2
205    2
206    0
207    1
208    0
209    2
210    2
211    2
212    2
213    1
214    0
215    2
216    2
217    0
218    2
219    2
220    2
221    2
222    2
223    2
224    2
225    2
226    2
227    2
228    2
229    2
230    2
231    2
232    2
233    2
234    2
235    2
236    2
237    2
238    2
239    0
240    1
241    2
242    2
243    0
244    1
245    2
246    2
247    2
248    2
249    2
250    2
251    2
252    2
253    2
254    0
255    0
256    2
257    0
258    2
259    1
260    2
261    2
262    2
263    1
264    2
265    2
266    2
267    2
268    2
269    2
270    2
271    2
272    0
273    1
274    2
275    2
276    2
277    1
278    2
279    1
280    2
281    2
282    2
283    2
284    0
285    2
286    2
287    2
288    1
289    2
290    0
291    0
292    2
293    2
294    0
295    0
296    2
297    2
298    0
299    1
300    1
301    2
302    1
303    2
304    2
305    0
306    0
307    0
308    0
309    0
310    0
311    2
312    2
313    2
314    2
315    2
316    2
317    2
318    0
319    2
320    2
321    1
322    2
323    2
324    0
325    2
326    2
327    2
328    0
329    1
330    2
331    2
332    2
333    2
334    2
335    2
336    0
337    2
338    2
339    2
340    2
341    2
342    2
343    2
344    2
345    2
346    2
347    2
348    2
349    2
350    2
351    0
352    2
353    0
354    2
355    2
356    2
357    1
358    1
359    2
360    0
361    0
362    2
363    1
364    2
365    0
366    0
367    1
368    0
369    0
370    2
371    2
372    0
373    2
374    0
375    2
376    0
377    0
378    2
379    0
380    0
381    2
382    2
383    2
384    2
385    2
386    2
387    1
388    0
389    2
390    2
391    2
392    0
393    2
394    2
395    2
396    2
397    2
398    2
399    2
400    2
401    2
402    2
403    2
404    2
405    2
406    2
407    2
408    2
409    2
410    1
411    1
412    2
413    2
414    2
415    2
416    2
417    2
418    2
419    0
420    1
421    2
422    2
423    2
424    2
425    2
426    2
427    1
428    2
429    2
430    2
431    2
432    2
433    2
434    2
435    2
436    2
437    2
438    2
439    2
440    2
441    2
442    2
443    2
444    2
445    2
446    2
447    0
448    2
449    2
450    2
451    0
452    0
453    2
454    0
455    2
456    2
457    2
458    1
459    2
460    2
461    2
462    2
463    2
464    2
465    2
466    2
467    1
468    0
469    2
470    2
471    2
472    0
473    2
474    2
475    2
476    2
477    2
478    2
479    2
480    2
481    2
482    2
483    0
484    2
485    2
486    0
487    2
488    2
489    2
490    2
491    2
492    0
493    2
494    0
495    0
496    2
497    2
498    2
499    2
500    1
501    1
502    2
503    2
504    0
505    2
506    2
507    2
508    2
509    1
510    2
511    2
512    0
513    2
514    2
515    2
516    1
517    2
518    2
519    2
520    2
521    0
522    0
523    0
524    1
525    2
526    2
527    2
528    2
529    2
530    0
531    0
532    0
533    2
534    2
535    2
536    0
537    2
538    0
539    2
540    2
541    2
542    2
543    0
544    2
545    2
546    0
547    2
548    2
549    0
550    2
551    1
552    0
553    2
554    2
555    0
556    0
557    2
558    2
559    1
560    2
561    2
562    2
563    2
564    2
565    2
566    2
567    0
568    2
569    2
570    2
571    2
572    1
573    2
574    2
575    2
576    2
577    0
578    2
579    2
580    0
581    2
582    0
583    0
584    2
585    2
586    0
587    2
588    2
589    2
590    0
591    2
592    1
593    2
594    2
595    2
596    2
597    0
598    0
599    2
600    2
601    2
602    2
603    0
604    2
605    2
606    2
607    0
608    2
609    2
610    2
611    1
612    1
613    2
614    2
615    2
616    2
617    2
618    2
619    0
620    2
621    0
622    2
623    2
624    2
625    1
626    2
627    2
628    1
629    2
630    2
631    0
632    2
633    2
634    2
635    2
636    2
637    2
638    2
639    2
640    0
641    2
642    2
643    0
644    0
645    2
646    0
647    2
648    2
649    2
650    2
651    2
652    1
653    1
654    2
655    2
656    1
657    2
658    0
659    2
660    0
661    2
662    2
663    2
664    2
665    2
666    2
667    2
668    2
669    2
670    2
671    2
672    2
673    2
674    2
675    2
676    2
677    2
678    0
679    1
680    0
681    2
682    2
683    2
684    0
685    2
686    2
687    2
688    2
689    2
690    0
691    2
692    0
693    2
694    2
695    2
696    1
697    0
698    2
699    0
700    2
701    0
702    1
703    2
704    2
705    2
706    2
707    2
708    0
709    0
710    2
711    2
712    2
713    2
714    2
715    0
716    2
717    1
718    2
719    2
720    2
721    2
722    2
723    2
724    2
725    2
726    1
727    2
728    2
729    2
730    0
731    2
732    2
733    2
734    2
735    2
736    0
737    2
738    2
739    2
740    2
741    0
742    2
743    2
744    2
745    2
746    2
747    2
748    1
749    2
750    2
751    2
752    2
753    2
754    2
755    2
756    2
757    2
758    2
759    2
760    2
761    0
762    2
763    2
764    2
765    0
766    1
767    1
768    2
769    2
770    2
771    2
772    0
773    2
774    2
775    1
776    2
777    1
778    2
779    0
780    2
781    2
782    2
783    2
784    2
785    2
786    1
787    2
788    0
789    1
790    2
791    2
792    0
793    2
794    2
795    2
796    2
797    0
798    2
799    2
800    2
801    2
802    0
803    2
804    2
805    2
806    2
807    2
808    2
809    2
810    2
811    2
812    2
813    2
814    2
815    2
816    0
817    2
818    2
819    2
820    2
821    2
822    2
823    2
824    1
825    2
826    0
827    1
828    0
829    2
830    0
831    2
832    2
833    0
834    2
835    2
836    2
837    0
838    2
839    2
840    0
841    0
842    2
843    2
844    2
845    0
846    2
847    0
848    2
849    2
850    0
851    2
852    2
853    2
854    2
855    2
856    0
857    0
858    2
859    2
860    2
861    2
862    2
863    2
864    0
865    2
866    2
867    2
868    2
869    2
870    2
871    2
872    0
873    0
874    2
875    2
876    2
877    0
878    2
879    2
880    2
881    2
882    2
883    1
884    2
885    2
886    2
887    0
888    1
Name: Embarked, dtype: int32

In [49]:
from sklearn.ensemble import RandomForestClassifier

In [51]:
rf_model=RandomForestClassifier(n_estimators=10000, max_features=2, oob_score=True)

In [52]:
rf_model

RandomForestClassifier(max_features=2, n_estimators=10000, oob_score=True)

In [53]:
features=["Sex","Age","Embarked","Pclass","SibSp","Fare"]

In [54]:
features

['Sex', 'Age', 'Embarked', 'Pclass', 'SibSp', 'Fare']

In [55]:
rf_model.fit(X=train[features],y=train["Survived"])

RandomForestClassifier(max_features=2, n_estimators=10000, oob_score=True)

In [56]:
rf_model.oob_score_

0.8098987626546682

# To find important of each independent Varibale

In [57]:
for features,imp in zip(features,rf_model.feature_importances_):
    print(features,imp)

Sex 0.26799153343689636
Age 0.270498173163956
Embarked 0.03416915001074348
Pclass 0.08816008951697596
SibSp 0.05263458347006015
Fare 0.28654647040136794